### ISSUE TITLE
Calendar responsiveness

### ISSUE THREAD

**Issue by Nic787** [ThemeFuse/Unyson-Events-Extension#10]
Hi,

how can I make a responsive calendar?

My calendar is squeezed on mobile.

Thank you

**Comment by Nic787** [comment]
UP!

Also, can you look into this weird thing when I have multiple date for one event?

http://terra.nicolas-duclos.com/events/groupe-de-therapie-pour-le-couple-parent/

**Comment by Nic787** [comment]
Responsive bug

http://image.noelshack.com/fichiers/2015/17/1429808374-responsive.png

**Comment by Nic787** [comment]
UP!

**Comment by Nic787** [comment]
Someone had a great idea on a forum. Why not make something that scroll from right to left to show events list on mobile?

Or make something like that : http://codecanyon.net/item/eventon-wordpress-event-calendar-plugin/1211017?ref=ashanjay

**Comment by seoand** [comment]
Hi! Just jumping to Unyson.
Looking currently at Events plugin. Can create "events" and assign "event categories", "location" and "dates" BUT : it doesn't assign correct path to the event:( I'm in localhost) http://localhost/wptheme1/fw-event-slug/event-unyson-tutvus-2/ "event-unyson-tutvus-2" is post title, from where is starting the "fw-event-slug" part of the permalink?
Also-  it places the event where it must be in calendar, but when trying to navigate to event-post page :
This Month:
Not Found

## Sorry, but you are looking for something that isn't here. + Search box

If to search then it previews the event post OK, but again - permalink (linked post title) is as above ie wrong.

Thx

**Comment by valeriuzdrobau** [comment]
Hi, 
@Nic787 each developer decides how it wants to display the calendar on the front end, we only present how to use functionality delivered with Unyson.

@seoand Make sure you have rewrite module enabled and try to access the page Settings-> Permalinks and save the settings once again, and then tell me if there are some changes.

`fw-event-slug` is part of permalink because it is used as a parameter for `register_post_type()` [here](https://github.com/ThemeFuse/Unyson-Events-Extension/blob/master/class-fw-extension-events.php#L97). You can change `fw-event-slug` with anything using filter `fw_ext_events_post_slug`.
Example:

```
if ( ! function_exists( '_filter_fw_ext_events_post_slug' ) ) {
    function _filter_fw_ext_events_post_slug( $slug ) {
        return 'something-else';
    }

    add_filter( 'fw_ext_events_post_slug', '_filter_fw_ext_events_post_slug' );
}
```

**Comment by seoand** [comment]
Hi,

Thx Valeriuz!
I tried at home with brand new Wordpress install and it (events and permalinks) worked like a charm.
Maybe there is some crappy overlappings in the theme i used at work- it is frome some older ebook i made custom theme from... Must look at its code... I posted my question too early - without looking for solutions (always to try with blank wordpress install). Anyway - happy to try further unyson :)
There is never possible to foresee all kind of misconfigurations with old systems and code i guess.

And
