### ISSUE TITLE
Featured image cannot be seen in event page

### ISSUE THREAD

**Issue by stefanwebdevity** [ThemeFuse/Unyson-Events-Extension#29]
Hi there!

I am using the Events extension, with the DocDirect theme.
I created an event, than added a featured image to it.  https://imgur.com/a/Q1I6M
Unfortunately, the featured image is not shown in the event page. [](https://imgur.com/a/f7k6q)

Please advise!

Thanks for the plugins. Great job.

**Comment by ViorelEremia** [comment]
The frontend single event is rewritten by the theme if theme doesn't have template single.php for event post type in ```yourTheme/framework-customizations/extensions/events/views/single.php``` when the template is post type ```post``` single.php. Contact your theme developer unyson/extension event doesn't provide a single.php template for post type event.

**Comment by stefanwebdevity** [comment]
Judging by you name, you are romanian. I am to, so...SALUT!

Eu am luat legatura cu DocDirect, si raspunsul lor a fost ca trebuie sa iau legatura cu Unyson.
Din ce mi-ai scris, inteleg ca trebuie sa fac eu un fisier single.php in adresa respectiva? Pentru ca eu nu am fisierul de events in extensii.

Sau ar trebui ca DocDirect sa imi ofere fisierul single.php?

Nu prea am inteles topica frazei scrise de tine si de aceea am nelamuriri.
Mersi frumos!

**Comment by ViorelEremia** [comment]
Write in english because other users can understand how we solved this issue. You need to create a file in ```wp-content/themes/yourChildTheme/framework-customizations/extensions/events/views/single.php``` for exemple single events from scratch theme: https://github.com/ThemeFuse/Scratch-Theme/blob/master/scratch-parent/framework-customizations/extensions/events/views/single.php
If you add this file in your child theme then probably css will not work because all css is rewritten by your theme author. You need to write some css for this single events or you can request this inplimentation from your theme author.
